language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo add-apt-repository ppa:travis-ci/zero-mq -y
  - sudo apt-get update
  - sudo apt-get install zero-mq

matrix:
  allow_failures:
    - rust: nightly
