language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q

addons:
  apt:
    packages:
    - build-essential
    - libzmq4
    - libzmq4-dev

matrix:
  allow_failures:
    - rust: nightly
