language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --features="tcp" --verbose --all

addons:
  apt:
    packages:
      - libzmq3-dev

before_install:
  - sudo apt-get update

matrix:
  allow_failures:
    - rust: nightly
