language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo add-apt-repository -y ppa:anton+/dnscrypt
  - sudo apt-get update
  - sudo apt-get install -y -qq libzmq3-dev libsodium-dev

matrix:
  allow_failures:
    - rust: nightly
