[package]
name = "meowth"
version = "0.0.2"
authors = ["Šarūnas Navickas"]

[dependencies]
time = "0.1.38"
chrono = "0.4.0"
log = "0.3"
env_logger = "0.4.3"
yaml-rust = "0.4.0"
getopts = "0.2.15"
hostname = "0.1.3"
json_str = "0.5.0"


statsd = "0.10.0"

elastic = "*"
serde_json = "1.0.6"
serde = "1.0.22"
serde_derive = "*"
elastic_derive = "*"

zmq = "*"
