[package]
name = "meowth"
version = "0.0.1"
authors = ["Šarūnas Navickas"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
elastic_derive = "*"
json_str = "*"
hostname = "*"

time = "*"
chrono = "*"

log = "*"
env_logger = "*"
zmq = "*"
statsd = "*"
yaml-rust = "*"
getopts = "*"
elastic = "*"
